experiment:
  name: mobileface-baseline
  seed: 1337

model:
  name: mobileface
  embedding_dim: 128
  width_multiplier: 0.75
  backbone_dropout: 0.1

training:
  dataset:
    train_manifest: data/manifests/train.json
    val_manifest: data/manifests/val.json
    image_size: 112
    grayscale_probability: 0.1
  optimizer:
    name: adamw
    lr: 0.001
    weight_decay: 0.01
    betas: [0.9, 0.999]
  scheduler:
    name: cosine_annealing_warmup
    warmup_epochs: 3
    total_epochs: 50
    min_lr: 1.0e-5
  batch_size: 128
  num_workers: 4
  precision: fp16
  epochs: 50

validation:
  frequency: 1
  metrics:
    - cosine_similarity
    - accuracy

checkpointing:
  dir: artifacts/checkpoints
  keep_last: 3
  save_best_metric: accuracy

export:
  onnx:
    opset: 17
    dynamic_axes: false
    quantize: true
